name: "Main Pipeline"

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
        types:
            - "opened"
            - "synchronize"

jobs:
    kill-previous-jobs:
        runs-on: ubuntu-18.04
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}
    lint:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14.18.1
                  cache: "yarn"
            - run: yarn install --frozen-lockfile
            - run: yarn lint
    build:
        needs: [lint]
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14.18.1
                  cache: "yarn"
            - run: yarn install --frozen-lockfile
            - run: yarn build
    test:
        needs: [lint]
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14.18.1
                  cache: "yarn"
            - run: yarn install --frozen-lockfile
            - run: yarn test
    deploy:
        needs: [build, test]
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v3
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
